# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../get_homolog_method.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Get_homolog_method(object):
    def setupUi(self, Get_homolog_method):
        Get_homolog_method.setObjectName("Get_homolog_method")
        Get_homolog_method.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Get_homolog_method)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.BDBH = QtWidgets.QRadioButton(Get_homolog_method)
        self.BDBH.setGeometry(QtCore.QRect(80, 70, 112, 23))
        self.BDBH.setObjectName("BDBH")
        self.OMCL = QtWidgets.QRadioButton(Get_homolog_method)
        self.OMCL.setGeometry(QtCore.QRect(80, 120, 112, 23))
        self.OMCL.setObjectName("OMCL")
        self.COG = QtWidgets.QRadioButton(Get_homolog_method)
        self.COG.setGeometry(QtCore.QRect(80, 170, 112, 23))
        self.COG.setObjectName("COG")
        self.UnifiedLTname = QtWidgets.QLineEdit(Get_homolog_method)
        self.UnifiedLTname.setGeometry(QtCore.QRect(80, 20, 271, 21))
        self.UnifiedLTname.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.UnifiedLTname.setAutoFillBackground(False)
        self.UnifiedLTname.setText("")
        self.UnifiedLTname.setObjectName("UnifiedLTname")
        self.percentSimilarity = QtWidgets.QLineEdit(Get_homolog_method)
        self.percentSimilarity.setGeometry(QtCore.QRect(80, 50, 271, 21))
        self.percentSimilarity.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.percentSimilarity.setAccessibleDescription("")
        self.percentSimilarity.setAutoFillBackground(False)
        self.percentSimilarity.setText("")
        self.percentSimilarity.setObjectName("percentSimilarity")


        self.retranslateUi(Get_homolog_method)
        self.buttonBox.accepted.connect(Get_homolog_method.accept) # type: ignore
        self.buttonBox.rejected.connect(Get_homolog_method.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Get_homolog_method)

    def retranslateUi(self, Get_homolog_method):
        _translate = QtCore.QCoreApplication.translate
        Get_homolog_method.setWindowTitle(_translate("Get_homolog_method", "GET_HOMOLOGOUS"))
        self.BDBH.setText(_translate("Get_homolog_method", "BDBH"))
        self.OMCL.setText(_translate("Get_homolog_method", "OMCL"))
        self.COG.setText(_translate("Get_homolog_method", "COG"))
        self.UnifiedLTname.setPlaceholderText(_translate("Get_homolog_method", "Enter unified locus name"))
        self.percentSimilarity.setPlaceholderText(_translate("Get_homolog_method", "Enter similarity %"))


    def get_data(self):#checked1
        if self.BDBH.isChecked():
            return "BDBH"
        elif self.OMCL.isChecked():
            return "OMCL"
        else:
            return "COG"
    
    def getUnifiedLT(self):#checked1
        return self.UnifiedLTname.text()

    def getSimilarity(self):#checked1
        return self.percentSimilarity.text()



def get_homolog_data():
    Data = QtWidgets.QDialog()
    ui = Ui_Get_homolog_method()
    ui.setupUi(Data)
    if Data.exec_():
        return (ui.get_data(), ui.getUnifiedLT(), ui.getSimilarity())
    else:
        return ()
