# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_Dialog2(object):
    def setupUi(self, Dialog2):
        Dialog2.setObjectName("Upload Data")
        Dialog2.resize(400, 300)
        self.Db_dir = QtWidgets.QLineEdit(Dialog2)
        self.Db_dir.setGeometry(QtCore.QRect(20, 80, 211, 31))
        self.Db_dir.setObjectName("Db_dir")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog2)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.Db_button = QtWidgets.QPushButton(Dialog2)
        self.Db_button.setGeometry(QtCore.QRect(230, 80, 141, 31))
        self.Db_button.setObjectName("Db_button")
        self.Db_button.clicked.connect(self.dbclicked)
        self.fastq_dir = QtWidgets.QLineEdit(Dialog2)
        self.fastq_dir.setGeometry(QtCore.QRect(20, 130, 211, 31))
        self.fastq_dir.setObjectName("fastq_dir")
        self.fastq_button = QtWidgets.QPushButton(Dialog2)
        self.fastq_button.setGeometry(QtCore.QRect(230, 130, 141, 31))
        self.fastq_button.setObjectName("fastq_button")
        self.fastq_button.clicked.connect(self.fqclicked)

        self.retranslateUi(Dialog2)
        self.buttonBox.accepted.connect(Dialog2.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog2.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog2)

    def retranslateUi(self, Dialog2):
        _translate = QtCore.QCoreApplication.translate
        Dialog2.setWindowTitle(_translate("Upload Path", "Upload Path"))
        self.Db_button.setText(_translate("Dialog2", "Upload"))
        self.Db_dir.setPlaceholderText(_translate("Dialog2", "Choose Database Dir"))
        self.fastq_dir.setPlaceholderText(_translate("Dialog2", "Choose Fastq Dir"))
        self.fastq_button.setText(_translate("Dialog2", "Upload"))

    def dbclicked(self):#checked1
        DBpath = QtWidgets.QFileDialog.getExistingDirectory(None, "DB path", directory=os.getcwd())
        self.Db_dir.setText(DBpath)
        
    
    def fqclicked(self):#checked1
        FQpath = QtWidgets.QFileDialog.getExistingDirectory(None, "FQ path", directory=os.getcwd())
        self.fastq_dir.setText(FQpath)
        
    def getdbpath(self):#checked1
        return self.Db_dir.text()

    def getfqpath(self):#checked1
        return self.fastq_dir.text()

def automatic_upload():
    Data2 = QtWidgets.QDialog()
    ui2 = Ui_Dialog2()
    ui2.setupUi(Data2)
    if Data2.exec_():
        return (ui2.getdbpath(), ui2.getfqpath())
    else:
        return ()

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
'''
